### ISSUE TITLE
Downloads not working because you need to joint the Chat-Channel to be able to download

### ISSUE THREAD

**Issue by GoodSoulGermany** [ostafen/xdcc-cli#7]
On many IRC chans you need to join the their main-chat channel (e.g. #mg-chat for #moviegods), else you can't download anything.

Is there a way to implement this?

**Comment by ostafen** [comment]
Hey, good question, I'm aware about that issue. The problem is that each channel notify the user about joining their chat chat channel using a human readable text message without a specific known structure, so I guess a generic solution to automatize that doesn't exist. But let me know if you know more about it.
